version: '3.3'
services:

  db:
    image: postgres:13.10
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - ../.env
  
  backend:
      image: gera1311/foodgram_backend:latest
      volumes:
        - static:/backend_static
        - media:/app/media_foodgram/
      depends_on:
        - db
      env_file:
        - ../.env

  frontend:
    image: gera1311/foodgram_frontend:latest
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static 
    depends_on:
      - backend
    env_file:
      - ../.env

  nginx:
    image: gera1311/foodgram_gateway:latest
    ports:
      - "80:80"
    volumes:
      - static:/var/html/static/
      - media:/var/html/media/
    depends_on:
      - frontend

volumes:
  db_data:
  static:
  media:
