# Generated by Django 4.2 on 2024-12-02 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shopping_Cart',
            new_name='ShoppingCart',
        ),
    ]
