# Generated by Django 4.2 on 2024-12-03 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_rename_shopping_cart_shoppingcart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'verbose_name': 'Продуктовая корзина', 'verbose_name_plural': 'Продуктовая корзина'},
        ),
    ]
