# Generated by Django 4.2 on 2024-12-29 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_recipe_is_in_shopping_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='is_in_shopping_cart',
        ),
    ]
